import { v4 as uuidv4 } from "uuid";
let data = [
    {   
        id: uuidv4(),
        avatar:'https://miro.medium.com/fit/c/30/30/1*2uZNASNFjSVqQxmFlE5yvA.jpeg',
        title:'UI/UX Design Trends of 2022',
        name: 'Codeart',
        topic:'Programming',
        updated:'Jan 26',
        isTrue: false,
        categoryId: '',
        read:'7',
        img:'https://miro.medium.com/fit/c/140/140/1*gfQL8iTqOKozDq10UZ_xxQ.jpeg',
        desc:'As 2021 is coming to a close, we are taking the time to review some of the most notable trends for the upcoming year.',
        text:`These past couple of years serve as particularly strong evidence of the constant and fast development happening in the UX/UI industry — both in terms of technologies and design trends implemented. Explorations are unfolding in all sorts of directions — some short-lived, some reimagined and some recurring with a greater focus than ever before. Below we present to you in greater detail some of the explorations that will stick throughout 2022.`

    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*QDJsKs7OV9h6R5aaMJaOFQ.png',
        title: '5 Concepts That Will Make You a Better React Developer',
        name: 'Henrik Larsen Toft',
        topic: 'Programming',
        updated: 'May 29',
        isTrue: false,
        categoryId: '',
        read: '4',
        img: 'https://miro.medium.com/fit/c/140/140/0*bfyviVoMX5tZ85GU',
        desc:'Learn how to leverage advanced React concepts to become a better React developer.',
        text: `  As you already know hooks are a new addition in React 16.8 that will let you use state and other React features without writing a class or component.Building your own custom hooks are a great way of extracting component logic into functions that can be reused and tested independently.`,

    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*rhvwW5suGypWKG_iJqFWcA.jpeg',
        title: '3 Free Machine Learning Courses You Should Take Right Now',
        name: 'Rebecca Vickery',
        topic: 'Programming',
        updated: 'May 28',
        isTrue: false,
        categoryId: '',
        read: '6',
        img: 'https://miro.medium.com/fit/c/140/140/1*JIRNLjwWq-YbFfRp9JJsZA.jpeg',
        desc: 'There are many ways to get started with studying machine learning. I have previously written a lot about how to design your own curriculum and roadmap as an alternative to taking courses',
        text: `This approach allows you to pick and choose free, or low-cost, resources from across the internet that suit both your learning style and budget.However, when you are just starting out on the beginning of your journey into machine learning it can often be useful to follow at least a short course that will guide you through the basic concepts first. This will give you a good foundational overview of the field and it will make it easier to design your own learning path and then continue on with deeper self-directed learning.`,
    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/60/60/1*KCxXwmPqMoulWutRuOZouA.jpeg',
        title: 'Trying to learn Arabic, as a Muslim — Reflections and thoughts (after a decade of attempts)',
        name: 'JG Hall',
        topic: 'Language',
        updated: 'May 31',
        isTrue: false,
        categoryId: '',
        read: '13',
        img: 'https://miro.medium.com/fit/c/140/140/1*J2jFGkLBGxi_oTwAAryyhA.jpeg',
        desc: 'In a decade, you can achieve much. You might complete an Undergrad or Master’s degree, you could get married and start a family, build a new career, or even, reach a level of native fluency in a second language.',
        text: `Yet, here I am, starting another Arabic course for the umpteenth time at the end of the month. I have made countless attempts to self-study, gone through more teachers than a monkey will go through bananas, and ‘lost’ money as quick as an amateur Crypto-bro, on Arabic lessons, books, and online resources. But, still cannot competently read a basic children’s book in Arabic without a dictionary nor (at least, not any longer), sustain a basic conversation.`,
    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*Xg7To9Xl0TTGbFlAuZ208Q.jpeg',
        title: 'How to Learn a Language with Google Translate and Podcasts',
        name: 'Maral',
        topic: 'Language',
        updated: 'May 14',
        isTrue: false,
        categoryId: '',
        read: '2',
        img: 'https://miro.medium.com/fit/c/140/140/0*Ukz343nK43jVhky2',
        desc: 'Lately, I’ve been challenging myself by combining passive learning methods with active learning methods in my language learning journey.',
        text: `Previously, I’ve mentioned in one of my articles how listening to podcasts in the target language can be a great addition to one’s learning journey.I had also mentioned in one of my articles how I used Google Translate at the beginning of my Swedish learning journey when I had no clue about the language, which helped me a lot in the beginning.`,
    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*lFWV94z6lweRTvmuxY_lOA.png',
        title: 'The Language of Intelligence',
        name: 'New Globe Utopia',
        topic: 'Language',
        updated: 'Aug 13',
        isTrue: false,
        categoryId: '',
        read: '4',
        img: 'https://miro.medium.com/fit/c/140/140/0*1wcOLbN30p2xQlbu',
        desc: 'For centuries, humanity has pondered the Intelligence that governs nature and Scientists have attempted to unravel the nature of the brain.',
        text: ` A consensus on the definition of intelligence has yet to happen, as intelligence has different definitions depending on the field of study. The prevailing theory today is that intelligence is local to the brain.The Unified Intelligence DAO is a decentralized, autonomous organization challenging this perspective with the belief that investigating the distinction between Human intelligence and nature’s intelligence can help humanity build more efficient and symbiotic systems. At The Unified Intelligence DAO, we believe that to build such Artificial Intelligence Systems, we must first understand General intelligence.`,
    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*XVE3BIo5q7-CWjJPt2rcfg.jpeg',
        title: 'Like We Know What’s Happening',
        name: 'Mike Hickman',
        topic: 'Social Media',
        updated: 'May 7',
        isTrue: false,
        categoryId: '',
        read: '3',
        img: 'https://miro.medium.com/fit/c/140/140/1*TK3hipBJeqgIKR8iUCQIEg.jpeg',
        desc: 'On September 26th, 1983, had it been around back then, the permanent mental excoriation that is Twitter’s “What’s Happening” sidebar would have entirely missed the fact that we were all in imminent danger of annihilation.',
        text: `If I’d had Twitter back then, my personal sidebar might conceivably look different from those of others around the world. (How do we know? How do we really know, without peering over the shoulders of everyone else using Twitter at the same time as us?) I’d expect, although the six-year-old me wouldn’t be terrifically interested, that there’d be an impolite #Thatcher hashtag or two. As Doctor Who’s 20th anniversary was approaching, and depending on how much the algorithm took notice of my own interests, there might have been the usual hashtag or three for that series. And perhaps the top movies of the day might have got a look in. Return of the Jedi, for definite, even if it was a few months old.`,
    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*XVE3BIo5q7-CWjJPt2rcfg.jpeg',
        title: '2 New Tools To Test On Instagram',
        name: 'Kasey Wagner',
        topic: 'Social Media',
        updated: 'March 8',
        isTrue: false,
        categoryId: '',
        read: '4',
        img: 'https://miro.medium.com/fit/c/140/140/1*c2pXATWEzdP2i0cH1rua_w.jpeg',
        desc: 'How Instagrams latest tools help both creators and brands reach a larger audience and drive sales.',
        text: `For both creators and brands, it’s safe to say that Instagram can be stressful at times. Keeping up with the latest Instagram features can be exhausting, especially when you’re making sure you’re quick to adapt and finding new ways to apply it to your content. With competition from TikTok, typically the goal of these new features is to increase engagement and encourage new ways of connecting with other users within the app. Reels has been a huge success on Instagram, mimicking the short form content of TikTok with features including morphing clips together, adding trending music, and the ability to add voice-over to name just a few of the ways the new video format has allowed creators to reach a larger audience.`,
    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*DEYlbQx86lHy9qnBqQbAhQ.png',
        title: '10 Things to Consider Before Becoming a Content Creator',
        name: 'Claudiu',
        topic: 'Social Media',
        updated: 'July 4',
        isTrue: false,
        categoryId: '',
        read: '7',
        img: 'https://miro.medium.com/fit/c/140/140/0*PHDxxEPdNzwceFCS',
        desc: 'If you’ve ever considered becoming a content creator, congratulations! The decision to start your own blog, podcast, or video series is an exciting one. After all, the world, or at least that part of it that’s online is your oyster',
        text: `If you’ve ever considered becoming a content creator, congratulations! The decision to start your own blog, podcast, or video series is an exciting one. After all, the world, or at least that part of it that’s online is your oyster.If you’ve ever considered becoming a content creator, congratulations! The decision to start your own blog, podcast, or video series is an exciting one. After all, the world, or at least that part of it that’s online is your oyster.`,
    },
    {
        id: uuidv4(),
        avatar: 'https://miro.medium.com/fit/c/30/30/1*-LYrFHhssflRu9pxAdbBZQ.jpeg',
        title: 'Top 10 Richest People in the World',
        name: 'Manoj Ahirwar',
        topic: 'World',
        updated: 'Dec 19',
        isTrue: false,
        categoryId: '',
        read: '1',
        img: 'https://miro.medium.com/fit/c/140/140/1*R6v7GgRUjD3hBa2etZT-Mw.jpeg',
        desc: 'These are the Top 10 wealthiest people in the world. as of 29th May 2022',
        text: `1. Elon Musk,2. Bernard Arnault & family,3. Jeff Bezos,4. Bill Gates,5. Warren Buffett,6. Gautam Adani & family,7. Larry Ellison,8. Larry Page,9. Mukesh Ambani,10. Carlos Slim Helu & family`,
    },
    //Add more topic

]
export default data